name: check

on:
  pull_request:
  push:
    branches:
      - main

# Cancel previous builds by only allowing one concurrent build per ref.
concurrency:
  group: bieter_tool_app_check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Get dependencies
      run: flutter pub get
    - name: Analyze
      run: flutter analyze
    - name: Run format check
      run: dart format -o none --set-exit-if-changed $(find . -name '*.dart' ! -name '*.g.dart' ! -name '*.freezed.dart' ! -path '*/generated/*' ! -path '*/gen/*')
